const falta = require('mongoose');

const Partes = falta.Schema({

    nom:String,
    grup:String,
    professor:String,
    atencio:Date,
    incident:Date,
    horari:Date,
    lloc:String,
    leve:String,
    grave:String,
    cboxA:String,
    cboxB:String,
    cboxC:String,
    cboxD:String,
    tasques:String,
    dias:Date,
    horas:Date,
    cboxE:String,
    diasExtraescolar:Date,
    diasExtraescolarFinal:Date,
    cboxF:String,
    clase:String,
    diasSuspensioClases:Date,
    diasSuspensioClasesFinal:Date,
    aLeve:String,
    bLeve:String,
    cLeve:String,
    dLeve:String,
    eLeve:String,
    fLeve:String,
    gLeve:String,
    hLeve:String,
    iLeve:String,
    jLeve:String,
    kLeve:String,
    lLeve:String,
    mLeve:String,
    nLeve:String,
    oLeve:String,
    pLeve:String,
    qLeve:String,
    rLeve:String,
    sLeve:String,

    aGrave:String,
    bGrave:String,
    cGrave:String,
    dGrave:String,
    eGrave:String,
    fGrave:String,
    gGrave:String,
    hGrave:String,
    iGrave:String,
    jGrave:String,
    kGrave:String,
    lGrave:String,
    mGrave:String,
    nGrave:String,
    oGrave:String,
    pGrave:String
},{
    timestamps:true
});


module.exports = falta.model('partes',Partes);